microsoft/Phi-3-mini-4k-instruct:
  per_device_train_batch_size: 1
  per_device_eval_batch_size: 1
  gradient_accumulation_steps: 8
  num_train_epochs: 1
  lora_rank: 8
  lora_alpha: 32
  lora_dropout: 0.1
